require "test_helper"

# The seam between our schema classes and RubyLLM.
#
# `RubyLLM::Chat#with_schema` does not hand the schema object to the provider.
# It calls `to_json_schema` and then reaches into the result for a particular
# key. Which key, and what `to_json_schema` returns, are both owned by gems we
# do not control -- and they have moved independently of each other. When they
# disagree the schema is dropped on the floor with no error at all, and the
# model answers in prose. BaseAgent#verify_schema_honored! exists because of
# that failure mode; these tests exist so it is visible before it ships.
class RubyLLMSchemaEnvelopeTest < ActiveSupport::TestCase
  include SchemaAssertions

  SCHEMAS = [
    Character::BaseSchema,
    Character::BackgroundSchema,
    Interaction::Schema,
    Location::OpeningSchema,
    Location::DetailSchema,
    Location::ExitsSchema
  ].freeze

  test "every schema class is a RubyLLM::Schema" do
    SCHEMAS.each { |schema| assert_operator schema, :<, RubyLLM::Schema }
  end

  # BaseAgent#missing_schema_keys relies on this class method to decide whether
  # a response honored the schema. Without it that check silently does nothing.
  test "every schema exposes its required properties to BaseAgent" do
    SCHEMAS.each do |schema|
      assert_respond_to schema, :required_properties
      assert_equal schema_required(schema), schema.required_properties.map(&:to_s)
    end
  end

  test "every schema produces a body RubyLLM can hand to a provider" do
    SCHEMAS.each do |schema|
      body = json_schema_body(schema)

      assert_equal "object", body["type"]
      assert body["properties"].present?
      assert body["required"].present?
    end
  end

  # This is the whole ball game: what `with_schema` actually stores. It is
  # asserted end to end rather than by reading `to_json_schema`, because the
  # bug this catches lives in the gap between the two.
  test "with_schema delivers our schema to the chat" do
    SCHEMAS.each do |schema|
      chat = RubyLLM::Chat.new(provider: :ollama, model: "gemma3:12b", assume_model_exists: true)
      chat.with_schema(schema)

      delivered = chat.schema

      assert_not_nil delivered,
                     "RubyLLM::Chat#with_schema dropped #{schema}: the model will be asked for " \
                     "structured output with no schema attached and will answer in prose."

      body = delivered.deep_stringify_keys
      body = body.fetch("schema") if body.key?("schema")

      assert_equal schema_properties(schema).keys, body["properties"].keys
      assert_equal schema_required(schema), body["required"].map(&:to_s)
    end
  end

  # What `with_schema` stores is the provider envelope, not the bare JSON
  # Schema: ruby_llm 1.16 keeps the wrapper (name + strict) and hands the whole
  # thing to the provider. ruby_llm 1.8.2 unwrapped it and kept only the body.
  # Pinned because it is the payload shape a provider actually receives.
  test "the delivered payload is the provider envelope, not a bare schema" do
    chat = RubyLLM::Chat.new(provider: :ollama, model: "gemma3:12b", assume_model_exists: true)
    chat.with_schema(Character::BaseSchema)

    delivered = chat.schema.deep_symbolize_keys

    assert_equal %i[name schema strict], delivered.keys
    assert_equal true, delivered[:strict]
    # The provider-visible schema name comes from the Ruby class name, with the
    # namespace separator flattened so it stays a legal identifier.
    assert_equal "Character__BaseSchema", delivered[:name]
    assert_match(/\A[A-Za-z0-9_-]+\z/, delivered[:name])
  end

  # The end of the wire. Everything above checks an intermediate hand-off; this
  # checks the request body a provider would actually receive. It is the only
  # assertion here that would have caught the silent drop on its own, and it is
  # the closest this suite can get to a live call without making one.
  test "the schema reaches the request body the provider is sent" do
    with_openrouter_key do
      chat = RubyLLM::Chat.new(provider: :openrouter, model: "minimax/minimax-m3", assume_model_exists: true)
      chat.with_schema(Interaction::Schema)
      chat.add_message(role: :user, content: "hello")

      response_format = render_payload(chat)[:response_format]

      assert_equal "json_schema", response_format[:type]
      assert_equal true, response_format.dig(:json_schema, :strict)
      assert_equal schema_properties(Interaction::Schema).keys,
                   response_format.dig(:json_schema, :schema, :properties).keys.map(&:to_s)
      assert_equal schema_required(Interaction::Schema),
                   response_format.dig(:json_schema, :schema, :required).map(&:to_s)
    end
  end

  # `strict` does not appear anywhere in this app's source. It is generated by
  # ruby_llm-schema and consumed by ruby_llm, and it lives in the envelope
  # rather than inside the JSON Schema body, where it is not a valid keyword.
  test "strict is an envelope flag, not a JSON Schema keyword we set" do
    body = json_schema_body(Character::BaseSchema)

    assert_equal false, body["additionalProperties"]
    assert_equal true, body["strict"], "ruby_llm-schema 0.4 still emits strict inside the body"
  end

  private

  # Reaches past the public API on purpose: rendering the payload is the only
  # way to see what a provider is sent without sending it. If a future RubyLLM
  # renames this, that is worth finding out about.
  def render_payload(chat)
    chat.instance_variable_get(:@provider).send(
      :render_payload,
      chat.messages,
      tools: {}, temperature: nil, model: chat.model, stream: false, schema: chat.schema
    )
  end

  # Building the OpenRouter provider needs its key present. Nothing here is
  # sent anywhere -- the payload is rendered and inspected in process.
  def with_openrouter_key
    original = RubyLLM.config.openrouter_api_key
    RubyLLM.config.openrouter_api_key = "sk-test-not-a-real-key"
    yield
  ensure
    RubyLLM.config.openrouter_api_key = original
  end
end
