FactoryBot.define do
  factory :playthrough do
    association :story
    # token is generated by has_secure_token on initialize.

    trait :started do
      character { association :character, story: story, is_protagonist: true }
      current_location { association :location, story: story }
    end

    trait :in_scene do
      current_location { association :location, story: story }
      current_scene { association :scene, story: story, location: current_location }
    end
  end
end
