# One of the kinds of person a universe is made of -- and, since the captain's
# ruling of 2026-09-04, one of the kinds of MONSTER too.
#
# A UNIVERSE'S BESTIARY IS THE MONSTROUS HALF OF ITS OWN RACE LIST. There is no
# second table and no second catalogue: `races.monstrous` is a parameter on the
# record that already answers "what kinds of thing live in this world", seeded
# by the same `universe.races` block, generated by the same call, and carrying
# the same `description` that every prompt reading a race already reads. It is
# `locations.mobile`'s shape -- a monstrous race is an ordinary race in every
# other respect, and what differs is who is written from it.
#
# `.peoples` AND `.monstrous` ARE THE TWO POOLS A GENERATED PERSON IS DRAWN
# FROM, and which one is drawn from is the room's own `danger`
# (`Location::DANGERS`). Nothing else in the app reads the flag to make a
# decision: hostility itself is derived from it once, at creation
# (`Character.hostile_by_default?`), and stored on the character.
#
# WHAT IT DOES *NOT* DO IS HIDE THE RACE FROM A PROMPT. The captain's answer to
# the scout's call C4, 2026-09-04: *"monstrous races should reach the prompts"*
# -- so a monstrous race is in `Universe#race_names` for the `:place` and
# `:dialogue` audiences exactly like any other, a room can be described knowing
# that the thing in the belfry exists, and an NPC can warn you about it. See
# `Universe::AUDIENCE_FIELDS`.
class Race < ApplicationRecord
  belongs_to :universe
  has_many :characters, dependent: :restrict_with_error

  validates :name, presence: true, uniqueness: { scope: :universe_id, case_sensitive: false }
  validates :description, presence: true

  # THE TWO POOLS. `peoples` is deliberately not called `ordinary`: what it
  # holds is the set of races a person of this world can be born into, which is
  # the word the prompts and the seed files already use.
  scope :monstrous, -> { where(monstrous: true) }
  scope :peoples, -> { where(monstrous: false) }
end
